[general]
show_icons = true
icon_theme = "Papirus-Dark"
theme = "default"

[plugins.applications]
prefix = ""

[plugins.runner]
prefix = "!"

[plugins.websearch]
prefix = "?"

[plugins.calc]
prefix = "="

[plugins.clipboard]
prefix = "@"

[plugins.symbols]
prefix = "e:"
