stylesheets: ["../../themes/catppuccin-mocha/hyprland-preview-share-picker.css"]
default_page: windows
hide_token_restore: true

window:
  height: 500
  width: 1000

image:
  resize_size: 500
  widget_size: 150

windows:
  min_per_row: 3
  max_per_row: 999
  clicks: 1
  spacing: 12

outputs:
  clicks: 1
  spacing: 6
  show_label: false
  respect_output_scaling: true

region:
  command: slurp -f '%o@%x,%y,%w,%h'
