[settings]
always_keep_download = false
always_keep_install = false

[tools]
node = "lts"
python = "latest"
ruby = { version = "latest", postinstall = "gem install rubocop ruby-lsp" }
go = "latest"
rust = "latest"
